### ISSUE TITLE
trouble installing

### ISSUE THREAD

**Issue by jzicker** [dinkelk/PyDyGraphs#10]
I am having trouble installing.  Here is the pip3 command and error return
sh-4.4$ pip3 install git+https://github.com/dinkelk/pydygraphs.git
Collecting git+https://github.com/dinkelk/pydygraphs.git
  Cloning https://github.com/dinkelk/pydygraphs.git to /tmp/pip-nf9bdw3_-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.5/tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-nf9bdw3_-b
uild/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-nf9bdw3_
-build/

**Comment by dinkelk** [comment]
I apologize, pydygraphs is not currently set up to be installed via `pip`. Please follow the installation instructions in the [README.md](https://github.com/dinkelk/PyDyGraphs/blob/master/README.md).
