### ISSUE TITLE
Cleaner String Formatting

### ISSUE THREAD

**Issue by janga1997** [dinkelk/PyDyGraphs#4]
First of all, great work!
This is just what I had been looking for weeks.
I would like to make this library a bit better. I was hoping I could start out cleaning up the string formatting, which there is a lot.
Instead of inserting variables by converting them to strings and plus signs around them,
Python's `.format()` method is much cleaner.

**Comment by dinkelk** [comment]
Thank you! I am definitely all for making the library better, cleaner, and more up to date. It was only recently converted from Python 2 to 3. Any improvements you make I'll readily review and merge in. Please feel free to submit a pull request.

**Comment by dinkelk** [comment]
Resolved in pull request https://github.com/dinkelk/PyDyGraphs/pull/5.
