### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by adiell** [dinkelk/PyDyGraphs#6]
I tried to install this per the instructions in the readme:
"Simply clone this repository and include the pydygraphs.py module in your Jupyter Notebooks."
but it did not work. What am I missing? Do I need to add something to the path? some other thing? (I'm newbie to python)

**Comment by janga1997** [comment]
The README is not updated, as a commit merged  just yesterday introduced some changes.

Check the Jupyter notebook in the examples directory for the intended usage.

**Comment by adiell** [comment]
Thank you @janga1997 !
I followed the example notebook and it works. I had to add `%matplotlib inline` though.

**Comment by janga1997** [comment]
@adiell Why would you need to add `%matplotlib inline`? This library is not based on matplotlib.
Could it be possible you are polluting the namespace with the matplotlib library?

**Comment by adiell** [comment]
@janga1997 I now see it works without `%matplotlib inline`. Not sure what was the issue. Thanks again.

**Comment by dinkelk** [comment]
Thanks @janga1997. Updated README in 928e5b5319f5747532aa370c0a19e3cc35b761d2.
